---
- name: 0.系统初始化
  gather_facts: false
  hosts: newnode 
  roles:
    - common
  tags: common 

- name: 1.部署Docker
  gather_facts: false
  hosts: newnode
  roles:
    - docker 
  tags: docker

- name: 2.部署K8S Node
  gather_facts: false
  hosts: newnode
  roles:
    - node
  tags: node

- name: 3.更新集群hosts
  gather_facts: false
  hosts: hostall
  tasks:
    - template: src=roles/common/templates/hostsall.j2 dest=/etc/hosts

- name: 4.允许NewNode加入集群
  gather_facts: false
  ignore_errors: yes
  hosts: master
  tasks:
    - shell: kubectl certificate approve $(kubectl get csr |awk '$NF~/Pending/{print $1}')
