---
# 这个剧本在所有节点上运行

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  
- name: 关闭swap
  lineinfile:
    dest: /etc/fstab
    regexp: "UUID.*swap"
    line: ""

- name: 即时生效
  shell: setenforce 0 ; swapoff -a

- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts 

- name: "Get Local Kernel Version"
  setup: filter=ansible_kernel
  register: kv

- name: "test"
  debug: msg="{{ kv  }}"

- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 分发kernel升级包
  copy: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "{{ software_dir }}/kernel-ml-*.x86_64.rpm"
  when: kv.ansible_facts.ansible_kernel.startswith('3') or kv.ansible_facts.ansible_kernel.startswith('2')

- name: 升级kernel版本
  shell: yum localinstall -y {{ tmp_dir }}/kernel-ml-* && grub2-set-default 0 && grub2-mkconfig -o /etc/grub2.cfg && grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)" && reboot
  when: kv.ansible_facts.ansible_kernel.startswith('3') or kv.ansible_facts.ansible_kernel.startswith('2')

- name: 分发dns配置文件
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: 同步系统时间
  yum: name=ntpdate state=present
- name: 同步系统时间
  shell: ntpdate time.windows.com

